name: Docker Publish

on:
  release:
    types:
      - published
  # push:
  #   tags:
  #    - releases/v?[1-9]+.[0-9]+.[0-9]+
  #   branches:
  #     - main

jobs:
  docker-publish:
    name: Publish to Docker Hub
    # if: startsWith( github.ref, 'refs/tags/releases/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Get version tag
        id: version_tag
        run: |
          [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
          echo "::set-output name=value::${GITHUB_REF#refs/tags/}"
      # - name: Bump version
      #   uses: remorses/bump-version@js
      #   id: version
      #   with:
      #     version_file: ./VERSION
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout code
      #   uses: actions/checkout@v3.0.2
      #   with:
      #     ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: |
            maxirus/meshcommander:latest
            maxirus/meshcommander:${{ github.event.release.tag_name }}
          labels: "version=${{ github.event.release.tag_name }}"
